Replace pannel with modern spelling panel
google/generative-ai-docs pull request #205
Opened 2023-12-24 08:38 UTC by nafSadh

## Description of the change

## Motivation

## Type of change
Choose one: (Bug fix | Feature request | Documentation | Other)

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added detailed comments to my code where applicable.
- [ ] I have verified that my change does not break existing code.
- [ ] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [ ] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

2024-01-11 04:30 UTC, markmcd approved these changes
Thank you! Especially for running nbfmt. Because it's such a good idea I've added it to the GH PR workflow for the templates/ directory too, but that means you'll need to rebase this change, sorry.

2024-01-11 18:29 UTC, MarkDaoust requested changes

2024-01-11 18:29 UTC, MarkDaoust commented on templates/aistudio_gemini_prompt_chat.ipynb
> +    },
```suggestion
    }
```

2024-01-11 18:29 UTC, MarkDaoust commented on templates/aistudio_gemini_prompt_chat.ipynb
> +      "toc_visible": true,
```suggestion
      "toc_visible": true
```

2024-01-11 18:31 UTC, MarkDaoust approved these changes

2024-01-11 18:35 UTC, MarkDaoust approved these changes

2024-01-11 18:35 UTC, merged

2024-01-16 08:45 UTC, nafSadh commented
Sorry didn't follow up here. Looks like Mark synced and merged it in. Thanks :D