Update inference-with-keras.ipynb segmentation mask function
google/generative-ai-docs pull request #472
Opened 2024-06-24 23:02 UTC by divyashreepathihalli

Improve segmentation mask rendering

2024-06-25 16:57 UTC, elisabandy requested changes

2024-06-25 16:57 UTC, elisabandy commented on site/en/gemma/docs/paligemma/inference-with-keras.ipynb
> -    {
the block containing the copyright looks like it's getting lost in the change and should be preserved

2024-06-25 16:57 UTC, elisabandy commented on site/en/gemma/docs/paligemma/inference-with-keras.ipynb
> +        "<a target=\"_blank\" href=\"https://ai.google.dev/gemma/docs/paligemma/fine-tuning-paligemma\"><img src=\"https://ai.google.dev/static/site-assets/images/docs/notebook-site-button.png\" heig
this link should not be changed

2024-06-25 16:57 UTC, elisabandy commented on site/en/gemma/docs/paligemma/inference-with-keras.ipynb
> +        "Project: /gemma/_project.yaml\n",
these should not be in the github copy of the notebook

2024-12-12 18:57 UTC, joefernandez commented
Closing this PR due to lack of activity. This change is out of sync: recommend restarting update with synced notebook.

2024-12-12 18:57 UTC, closed without merging